### ISSUE TITLE
next button on network play continually starts other songs if tapped to fast

### ISSUE THREAD

**Issue by syleishere** [florent37/Flutter-AssetsAudioPlayer#538] opened 2021-05-05 15:44 UTC
```
medias2.add(myaudio.Audio.network(song1));
medias2.add(myaudio.Audio.network(song2));
medias2.add(myaudio.Audio.network(song3));
medias2.add(myaudio.Audio.network(song4));
await audioPlayer!.open(myaudio.Playlist(audios: medias2), loopMode: myaudio.LoopMode.playlist);
```

then tapping quickly on: `await audioPlayer!.next();`
will have like a million songs playing, doesn't matter what options I set to next() or even if I added a stop() before the next, it just continually starts new songs if you tap on next() repetitively quickly.

**Comment by syleishere** [comment] 2021-05-05 16:17
this is only happening on android from my testing, does same thing on pixel 4 XL real device as well as any of the android TV emulators from my testing.

**Comment by Mayb3Nots** [comment] 2021-05-11 05:53
You have to `await `for the `next `function to finish then only allow the button to run the `next `functions again.

**Comment by syleishere** [comment] 2021-05-11 13:46
I even have an await stop and await next, it doesn't matter, on android it just keeps playing new songs hitting next button all the time, seems to work fine on web, but not on any android emulators or my Pixel 4XL.

**Comment by syleishere** [comment] 2021-05-11 14:39
```
import 'package:flutter/material.dart';
import 'package:assets_audio_player/assets_audio_player.dart' as myaudio;

void main() async {
  return runApp(new MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  myaudio.AssetsAudioPlayer ?audioPlayer;

  @override
  void initState() {
    super.initState();
    openplayer();
  }

  openplayer() async {
    audioPlayer = myaudio.AssetsAudioPlayer();
    List<myaudio.Audio> medias2 = <myaudio.Audio>[];
    var song =
        'https://fastapi.sunsaturn.com/playlists/${Uri.parse("syleishere@gmail.com")}/${Uri.parse("default")}/${Uri.parse("newday.mp3")}';
    medias2.add(myaudio.Audio.network(song));
    song =
        'https://fastapi.sunsaturn.com/playlists/${Uri.parse("syleishere@gmail.com")}/${Uri.parse("default")}/${Uri.parse("Dirty Dancing - Hungry Eyes.mp3")}';
    medias2.add(myaudio.Audio.network(song));

    await audioPlayer!.open(myaudio.Playlist(audios: medias2),
        loopMode: myaudio.LoopMode.playlist, autoStart: true);
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return ElevatedButton(
        onPressed: () async { await audioPlayer!.next(); }, child: Text("Next Button Click me"));
  }
}
```

**Comment by syleishere** [comment] 2021-05-11 14:39
Just keep clicking next button quickly and you will see they start just playing new songs on android.

**Comment by Mayb3Nots** [comment] 2021-05-11 14:49
As expected, I dont have to run your code and I know that it will have that issue. When I say you have to wait before you run `next `again i mean you have to make sure it ends first. 

So like this
```
bool nextDone = true;
ElevatedButton(
        onPressed: () async { 
           if(nextDone){
              nextDone = false;
              await audioPlayer!.next();
              nextDone = true;
           }
         ; }, 
        child: Text("Next Button Click me")
);

**Comment by Mayb3Nots** [comment] 2021-05-11 14:50
This is a duplicate of #514. Take a look over there to get more info.

**Comment by syleishere** [comment] 2021-05-11 14:59
Oww a cancellable Future, never would have guessed that, alright I will accommodate for that, should I be doing this then for all controls? previous, play, stop as well as next?

**Comment by syleishere** [comment] 2021-05-11 17:01
If I display all the tracks on the playlist, and a user clicks on a song with a playlist playing, what is best way to handle that? 
Do I just call next and previous multiple times to try and move it to that song on playlist?

**Comment by syleishere** [comment] 2021-05-11 22:51
Running into same problem with playlistPlayAtIndex:

```
         if(nextDone) {
            nextDone = false;
            audioPlayer!.playlistPlayAtIndex(i);
            nextDone = true;
          }
```
If I click quickly with my mouse on android emulator on same song repeatedly, it starts playing new songs.

**Comment by Mayb3Nots** [comment] 2021-05-12 03:52
Did you `await `it?

**Comment by syleishere** [comment] 2021-05-12 05:12
Omg can't believe I forgot the await lol, coding to long today, thank-you for catching that.

**Comment by Mayb3Nots** [comment] 2021-05-16 12:42
@syleishere could you please close this. Thanks

**Closed** 2021-05-16 16:04 UTC
Labels: bug

**Comment by abhaysharma309** [comment] 2023-02-09 07:34
@kalismeras61 when i click on next button on ios notification panel plays two song at a time having issue only ios

Any solution regarding this ?
