### ISSUE TITLE
Couldn't find any option to add song in next playing queue.

### ISSUE THREAD

**Issue by yubarajshrestha** [florent37/Flutter-AssetsAudioPlayer#551] opened 2021-05-24 16:52 UTC
I already have my Playlist playing. let's say there are 5 songs in it and currently playing song is the third one so basically it's index 2. How can I get the index of currently playing item? Note, there can be same song twice in the playlist.
```
playlist = [
"audio_1",
"audio_2",
"audio_1",
"audio_3",
"audio_4"
]
```
The third item is audio_1 which is also in the first item, how to get index of currently playing item if the item currently playing is the third one.

**Comment by acuedd** [comment] 2021-05-24 21:15
You can Use the listener of current, example: 

```
AssetsAudioPlayer _audioPlayer = AssetsAudioPlayer(); 
_audioPlayer.current.listen((playingAudio) {
    print(playingAudio.playlist.currentIndex) // Here you can get the current index of your playlist
    // in the object playingAudio you have other options to get more information for example: nextIndex, prevIndex
}
```

I hope that can be of help to you.

**Comment by acuedd** [comment] 2021-05-24 21:20
@yubarajshrestha I think you should change  the label of this issue because it's not a bug, it's a **help wanted**

**Comment by kalismeras61** [comment] 2021-05-25 11:13
we have listeners for getting current index and also you can get it like below. 

```
AssetsAudioPlayer _audioPlayer = AssetsAudioPlayer(); 
_audioPlayer.current.value.playlist.currentIndex 
```

closing

**Closed by kalismeras61** 2021-05-25 11:13 UTC
Labels: help wanted
