### ISSUE TITLE
Audio not plying on mac and iOS browser only.

### ISSUE THREAD

**Issue by abdullah432** [florent37/Flutter-AssetsAudioPlayer#257] opened 2020-06-28 19:00 UTC
**Flutter Version**
Channel master
**Lib Version**
assets_audio_player: ^2.0.6+4

**Platform (Android / iOS / web) + version**
Platform : web

**Describe the bug**
Audio is playing on android, iOS, and web(window) but not working on Mac and iOS browser/web.

**Mac browser console error**
```
channel_buffers.dart:142 Overflow on channel: plugins.flutter.io/path_provider.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
J7 @ channel_buffers.dart:142
(anonymous) @ plugin_registry.dart:81
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
a1f @ plugin_registry.dart:78
fD @ plugin_registry.dart:78
eval @ VM320:3
P8 @ window.dart:617
Xk @ window.dart:459
oZ @ binding.dart:291
(anonymous) @ platform_channel.dart:151
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
UN @ platform_channel.dart:149
bM @ platform_channel.dart:149
KK @ platform_channel.dart:334
(anonymous) @ path_provider.dart:60
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
QB @ path_provider.dart:60
(anonymous) @ assets_audio_player.dart:1322
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
QD @ assets_audio_player.dart:1321
iv @ main.dart.js:31723
(anonymous) @ assets_audio_player.dart:1305
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
TO @ assets_audio_player.dart:1302
pG @ main.dart.js:31698
(anonymous) @ assets_audio_player.dart:938
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
VO @ assets_audio_player.dart:933
iB @ main.dart.js:31494
(anonymous) @ assets_audio_player.dart:735
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
VQ @ assets_audio_player.dart:734
q_ @ main.dart.js:31390
(anonymous) @ assets_audio_player.dart:1056
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
VP @ assets_audio_player.dart:1028
vG @ main.dart.js:31579
(anonymous) @ assets_audio_player.dart:1097
(anonymous) @ main.dart.js:3653
$2 @ main.dart.js:26505
P @ main.dart.js:3639
a39 @ assets_audio_player.dart:1088
os @ main.dart.js:31596
$0 @ assets_audio_player.dart:285
z_ @ main.dart.js:35765
DB @ ink_well.dart:992
$0 @ ink_well.dart:1098
Ij @ recognizer.dart:170
cE @ main.dart.js:34690
I0 @ tap.dart:523
C8 @ tap.dart:284
dD @ tap.dart:256
Bv @ arena.dart:155
hT @ binding.dart:222
a_Y @ binding.dart:198
v2 @ binding.dart:147
TQ @ window.dart:31
eval @ VM348:3
axI @ window.dart:764
VH @ pointer_binding.dart:128
eval @ VM324:3
$1 @ pointer_binding.dart:479
$1 @ pointer_binding.dart:440
$1 @ semantics.dart:1292
aHt @ js_helper.dart:1834
(anonymous) @ js_helper.dart:1857
Show 52 more frames
js_helper.dart:1129 Uncaught MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    at Object.k (http://demo.opzoom.com/main.dart.js:2260:3)
    at http://demo.opzoom.com/main.dart.js:46618:15
    at apD.a (http://demo.opzoom.com/main.dart.js:3653:71)
    at apD.$2 (http://demo.opzoom.com/main.dart.js:26505:23)
    at aoT.$1 (http://demo.opzoom.com/main.dart.js:26497:30)
    at Om.zq (http://demo.opzoom.com/main.dart.js:27525:41)
    at Om.m1 (http://demo.opzoom.com/main.dart.js:27527:30)
    at agF.$0 (http://demo.opzoom.com/main.dart.js:26932:11)
    at Object.pQ (http://demo.opzoom.com/main.dart.js:3777:40)
    at aj.mN (http://demo.opzoom.com/main.dart.js:26839:3)
```

**This is the sample of code, I used to play video but it's only failed on mac(web)**

```
IconButton(
                icon: Icon(
                  Icons.refresh,
                  color: Colors.white,
                  size: 40,
                ),
                onPressed: () {
                  try {
                    _assetAudioPlayer.open(Audio("assets/audio/lineage11.m4a"));
                    setState(() {
                      playing = true;
                    });
                  } catch (e) {
                    print(e.toString());
                  }
                }),
          )
```
```

**Comment by florent37** [comment] 2020-07-02 13:29
should be fixed, can you try `2.0.7+7` and reopen this ticket (with an exception) if this not work ?

the cause was because on mac I had to copy assets to a tmp directory, but it happened too on browser, I skiped it on web

**Closed by florent37** 2020-07-02 13:29 UTC
Labels: bug
