### ISSUE TITLE
Can not build on iOS devices

### ISSUE THREAD

**Issue by huy-t** [florent37/Flutter-AssetsAudioPlayer#30] opened 2020-02-29 11:08 UTC
```

           2020-02-29 18:06:02.704 xcodebuild[14409:311592]  DTDeviceKit: deviceType from 1394652bb7fc960ff7fbc21ce6f000aa2289e4f1 was NULL
[   +4 ms] Failed to build iOS app
[        ] Error output from Xcode build:
           ↳
[        ]     2020-02-29 18:05:58.332 xcodebuild[14387:311248]  DTDeviceKit: deviceType from a5a68d8f8f628f8e7c8ac56b2889580522c21d31 was NULL
               2020-02-29 18:05:58.424 xcodebuild[14387:311244]  DTDeviceKit: deviceType from a5a68d8f8f628f8e7c8ac56b2889580522c21d31 was NULL
               2020-02-29 18:05:58.775 xcodebuild[14387:311320]  DTDeviceKit: deviceType from 1394652bb7fc960ff7fbc21ce6f000aa2289e4f1 was NULL
               ** BUILD FAILED **


[        ] Xcode's output:
           ↳
[        ]     /Users/truonghuy/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:114:65: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
                               try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault, options: [])
                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                               AVAudioSession.Category.playback
               AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
               public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
                          ^
               /Users/truonghuy/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:114:103: error: 'AVAudioSessionModeDefault' has been renamed to 'AVAudioSession.Mode.default'
                               try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault, options: [])
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                     AVAudioSession.Mode.default
               AVFoundation.AVAudioSessionModeDefault:3:12: note: 'AVAudioSessionModeDefault' was obsoleted in Swift 3
               public let AVAudioSessionModeDefault: AVAudioSession.Mode
                          ^
               /Users/truonghuy/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:116:36: error: ambiguous reference to member 'setCategory'
                               try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: .mixWithOthers)
                                   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
               AVFoundation.AVAudioSession:22:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category) throws
                             ^
               AVFoundation.AVAudioSession:24:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category, options: AVAudioSession.CategoryOptions = []) throws
                             ^
               AVFoundation.AVAudioSession:27:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category, withOptions options: AVAudioSession.CategoryOptions = []) throws
                             ^
               AVFoundation.AVAudioSession:29:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category, mode: AVAudioSession.Mode, options: AVAudioSession.CategoryOptions = []) throws
                             ^
               AVFoundation.AVAudioSession:31:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category, mode: AVAudioSession.Mode, policy: AVAudioSession.RouteSharingPolicy, options: AVAudioSession.CategoryOptions = []) throws
                             ^
               AVFoundation.AVAudioSession:34:15: note: found this candidate
                   open func setCategory(_ category: AVAudioSession.Category, mode: AVAudioSession.Mode, routeSharingPolicy policy: AVAudioSession.RouteSharingPolicy, options: AVAudioSession.CategoryOptions = []) throws
                             ^
               note: Using new build system
               note: Planning build
               note: Constructing build description

[   +3 ms] Could not build the precompiled application for the device.
```

**Comment by jesusrp98** [comment] 2020-03-01 14:58
Same issue here :/

**Comment by florent37** [comment] 2020-03-01 14:59
please update your project to make it compatible with swift (see other issues on iOS)

**Comment by mechanized-mischief** [comment] 2020-03-03 20:11
Same issue here :(

**Comment by florent37** [comment] 2020-03-06 08:46
duplicate of : https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/29

**Comment by florent37** [comment] 2020-03-06 08:46
https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/29#issuecomment-590537548

**Closed by florent37** 2020-03-06 08:46 UTC
