### ISSUE TITLE
Compile error for ios

### ISSUE THREAD

**Issue by sinojelly** [florent37/Flutter-AssetsAudioPlayer#256] opened 2020-06-28 11:26 UTC
**Flutter Version**

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.17.4 at /Users/jelly/develop/flutter
    • Framework revision 1ad9baa8b9 (11 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jelly/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jelly/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

**Lib Version**

My version : assets_audio_player: ^2.0.6+4

**Platform (Android / iOS / web) + version**

Platform : iOS

**Describe the bug**

I can build it for android successfully. But failed to build it for ios.

**When I compile in XCode, It says:**
my_app/ios/Runner/GeneratedPluginRegistrant.m:10:9: Module 'assets_audio_player' not found

**When I run pod install in ios directory, It says:**

[!] Unable to determine Swift version for the following pods:

- `assets_audio_player` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by florent37** [comment] 2020-06-29 11:32
it's a duplicate of https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/230

it happen some times on some flutter projects

you have to do this  https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/230#issuecomment-646662832

tell me if it does not work :)

**Closed by florent37** 2020-06-29 11:32 UTC
Labels: bug

**Comment by sinojelly** [comment] 2020-07-04 11:35
> it's a duplicate of #230
> 
> it happen some times on some flutter projects
> 
> you have to do this [#230 (comment)](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/230#issuecomment-646662832)
> 
> tell me if it does not work :)

Without success using #230 (comment)
At last I fixed it by adding an empty swift file to my flutter ios project
See https://github.com/flutter/flutter/issues/16049#issuecomment-382664356

**Comment by Srini-B** [comment] 2020-07-17 10:43
Im on flutter v 1.17.5, Xcode 11.5, plugin v ^2.0.8. there is already Bridging Header file linked, I tried file - new - file - swift
but I didn't get any popup regarding bridging.

![Screenshot 2020-07-17 at 4 07 43 PM](https://user-images.githubusercontent.com/22414119/87778044-2f995580-c848-11ea-8e63-c06f32828940.png)
![Screenshot 2020-07-17 at 4 08 22 PM](https://user-images.githubusercontent.com/22414119/87778054-34f6a000-c848-11ea-86e7-553ba704b97d.png)
![Screenshot 2020-07-17 at 4 09 03 PM](https://user-images.githubusercontent.com/22414119/87778060-388a2700-c848-11ea-905a-70fef6a5a63b.png)
![Screenshot 2020-07-17 at 4 09 15 PM](https://user-images.githubusercontent.com/22414119/87778067-3b851780-c848-11ea-84e3-ee0bbf340177.png)

**Comment by Rizayev** [comment] 2021-02-05 01:26
I got the same problem 
![screenshot](https://user-images.githubusercontent.com/3787054/106976843-9180c480-6772-11eb-8d6a-c39a0a8f0af7.png)
