### ISSUE TITLE
rxdart problem

### ISSUE THREAD

**Issue by zszen** [florent37/Flutter-AssetsAudioPlayer#8] opened 2019-05-18 12:52 UTC
`Because XXXX  depends on assets_audio_player 1.0.1 which depends on rxdart ^0.20.0, rxdart ^0.20.0 is required.

So, because XXXX depends on rxdart 0.22.0, version solving failed.`

I must downgrade rxdart from 0.22.0 to 0.20.0

**Comment by AirborneEagle** [comment] 2020-01-31 02:12
This seems like a duplicate of #9

**Comment by florent37** [comment] 2020-02-16 15:11
fixed

**Closed by florent37** 2020-02-16 15:11 UTC
